강의상세페이지 베이스 구현
wecode-bootcamp-korea/39-2nd-Wemong-backend pull request #5
Opened 2022-12-02 07:27 UTC by Kimsu10

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성 
-강의 상세 페이지에서 기본적인  정보를 가져올수 있도록 구현함 

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- lectureId에 맞는 정보를 꺼내올 수 있도록 만들었습니다.

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![스크린샷 2022-12-02 오후 4 22 15](https://user-images.githubusercontent.com/107941176/205238048-9e4c40d7-f5a5-487e-9323-10654c9329b9.png)
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-05 03:27 UTC, Kang-kyunghun requested changes

2022-12-05 03:27 UTC, Kang-kyunghun commented on api/controllers/index.js
> +>>>>>>> 8141dbf (클래스사용 BUT 유닛테스트 문제 해결중)
컨플릭트 해결 잔해가 남아 있습니다.

항상 push 후에는 github의 Files changed 텝을 꼭확인 해주세요.

2022-12-05 03:27 UTC, Kang-kyunghun commented on api/controllers/lectureController.js
> +});
가독성을 위해 if나 for가는 새로구 구문들 사이에 공백을 추가해 주면 좋을 것 같습니다.
```suggestion
const  getLectureByLectureId = catchAsync ( async (req, res) => {
    const lectureId = req.params.lectureId;
    
    if(!lectureId) throw new CustomError( 'BAD REQUEST', 400)
    
    const detail = await lectureService.getLectureByLectureId(lectureId);
    return res.status(200).json({ data: detail });
});
```

2022-12-06 02:39 UTC, Kimsu10 commented on api/controllers/index.js
> +>>>>>>> 8141dbf (클래스사용 BUT 유닛테스트 문제 해결중)
수정했습니다! 이상하게 에러났다고 vs코드에안뜨더라고요   파일체인지드 항상 확인하겠습니다!

2022-12-06 02:58 UTC, Kang-kyunghun commented
고생 하셨습니다.

2022-12-06 02:58 UTC, merged